import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
DOCS = ["threat-model.md", "risk-register.md", "model-card.md"]
SRC_DIRS = ("guardrails/", "hooks/", "memory/", "publish/", "evals/", "pipeline/", "clarify/")


def named_paths(text: str) -> set[str]:
    return set(re.findall(r"`([\w./-]+\.(?:py|md|yaml|yml|sqlite|json))`", text))


def resolve(path: str) -> bool:
    candidates = [ROOT / path, ROOT / "src" / "story_agent" / path]
    return any(c.exists() for c in candidates) or "<" in path


@pytest.mark.parametrize("name", DOCS)
def test_every_file_a_doc_names_exists(name: str) -> None:
    text = (ROOT / "docs" / name).read_text(encoding="utf-8")
    missing = sorted(p for p in named_paths(text) if not resolve(p))
    assert missing == []


@pytest.mark.parametrize("name", DOCS)
def test_every_directory_a_doc_names_exists(name: str) -> None:
    text = (ROOT / "docs" / name).read_text(encoding="utf-8")
    dirs = set(re.findall(r"`((?:tests|src|config|docs|prompts|skill)/[\w./-]*/)`", text))
    assert [d for d in dirs if not (ROOT / d).exists()] == []


def test_the_model_card_prompt_versions_match_the_prompts() -> None:
    card = (ROOT / "docs" / "model-card.md").read_text(encoding="utf-8")
    rows = re.findall(r"^\| (\w+) \| (\d+) \|", card, re.M)
    listed = dict(rows)
    for prompt in (ROOT / "prompts").glob("*.md"):
        if prompt.name == "CHANGELOG.md":
            continue
        version = re.search(r"^version: (\d+)$", prompt.read_text(encoding="utf-8"), re.M)
        assert version, prompt.name
        assert listed.get(prompt.stem) == version.group(1), prompt.name
    assert set(listed) == {p.stem for p in (ROOT / "prompts").glob("*.md")} - {"CHANGELOG"}


def test_the_model_card_names_the_configured_models() -> None:
    card = (ROOT / "docs" / "model-card.md").read_text(encoding="utf-8")
    models = (ROOT / "config" / "models.yaml").read_text(encoding="utf-8")
    for key in ("generator", "judge"):
        value = re.search(rf"^{key}: (\S+)", models, re.M)
        assert value
        assert value.group(1) in card


def test_the_docs_make_no_certification_claim_and_name_no_author_tool() -> None:
    forbidden = ("certified", "is compliant", "fully compliant", "generated by", "co-authored")
    for name in DOCS:
        text = (ROOT / "docs" / name).read_text(encoding="utf-8").lower()
        assert not [w for w in forbidden if w in text], name


def test_risk_ids_are_numbered_without_gaps_and_open_items_exist() -> None:
    register = (ROOT / "docs" / "risk-register.md").read_text(encoding="utf-8")
    table, rest = register.split("## Open items", 1)
    ids = re.findall(r"^\| (R\d{2}) \|", table, re.M)
    open_ids = re.findall(r"^\| (R\d{2})", rest, re.M)
    assert set(open_ids) <= set(ids)
    assert ids == [f"R{n:02d}" for n in range(1, len(ids) + 1)]
    assert len(ids) >= 18
